name: CI Test - install stable & nightly
on:
  push:
    branches:
      - main
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main
  schedule:
    # Every Monday at midnight: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: "0 0 * * 1"
permissions:
  contents: read
concurrency:
  # Cancel old actions upon push
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  install_on_runner:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        toolchain:
          - stable
          - nightly
          - beta
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use myself
        id: toolchain
        uses: ./
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true

      - name: Test action outputs
        env:
          RUSTC: ${{ steps.toolchain.outputs.rustc }}
          RUSTC_HASH: ${{ steps.toolchain.outputs.rustc_hash }}
          CARGO: ${{ steps.toolchain.outputs.cargo }}
          RUSTUP: ${{ steps.toolchain.outputs.rustup }}
        run: |
          echo "$RUSTC" && test "$RUSTC" != ""
          echo "$RUSTC_HASH" && test "$RUSTC_HASH" != ""
          echo "$CARGO" && test "$CARGO" != ""
          echo "$RUSTUP" && test "$RUSTUP" != ""
  install_in_docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
          - beta
    # Docker image, not the GitHub Actions VM
    container: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # `rustup` will need `curl` or `wget` later
      - name: Install packages
        run: apt-get update && apt-get install -y curl

      - name: Use myself
        id: toolchain
        uses: ./
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true

      - name: Test action outputs
        env:
          RUSTC: ${{ steps.toolchain.outputs.rustc }}
          RUSTC_HASH: ${{ steps.toolchain.outputs.rustc_hash }}
          CARGO: ${{ steps.toolchain.outputs.cargo }}
          RUSTUP: ${{ steps.toolchain.outputs.rustup }}
        run: |
          echo "$RUSTC" && test "$RUSTC" != ""
          echo "$RUSTC_HASH" && test "$RUSTC_HASH" != ""
          echo "$CARGO" && test "$CARGO" != ""
          echo "$RUSTUP" && test "$RUSTUP" != ""
